-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 20:55:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8 ;
USE `myapp` ;

-- -----------------------------------------------------
-- Table `myapp`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Customer` (
  `email` VARCHAR(100) NOT NULL,
  `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `billing_address` VARCHAR(256) NOT NULL,
  `birth_date` DATE NOT NULL,
  `mailing_address` VARCHAR(256) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `last_login` DATETIME NOT NULL,
  `date_created` datetime NOT NULL,
  `subscribed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Genre` (
  `genre_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `genre_description` TEXT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Product` (
  `ISBN13` CHAR(14) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `type` CHAR(20) NOT NULL,
  `publisher` VARCHAR(256) NOT NULL,
  `release_date` DATE NOT NULL,
  `language` CHAR(20) NOT NULL,
  `description` TEXT NULL,
  `length` INT NOT NULL,
  `rating` INT NULL,
  `no_of_downloads` INT NULL,
  `unit_price` DECIMAL(5,2) NULL,
  `file_size` VARCHAR(10) NULL,
  `author` VARCHAR(50) NOT NULL,
  `Genre_genre_id` SMALLINT NOT NULL,
  PRIMARY KEY (`ISBN13`, `Genre_genre_id`),
  INDEX `fk_Product_Genre1_idx` (`Genre_genre_id` ASC),
  CONSTRAINT `fk_Product_Genre1`
    FOREIGN KEY (`Genre_genre_id`)
    REFERENCES `myapp`.`Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`OrderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`OrderDetail` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `unit_price` DECIMAL(5,2) NOT NULL,
  `datetime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Customer_email` VARCHAR(100) NOT NULL,
  `Product_ISBN13` CHAR(14) NOT NULL,
  PRIMARY KEY (`order_id`, `Customer_email`, `Product_ISBN13`),
  INDEX `fk_Transaction_Customer_idx` (`Customer_email` ASC),
  INDEX `fk_OrderDetail_Product1_idx` (`Product_ISBN13` ASC),
  CONSTRAINT `fk_Customer_email`
    FOREIGN KEY (`Customer_email`)
    REFERENCES `myapp`.`Customer` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OrderDetail_Product1`
    FOREIGN KEY (`Product_ISBN13`)
    REFERENCES `myapp`.`Product` (`ISBN13`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`CardInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`CardInfo` (
  `card_no` VARCHAR(20) NOT NULL,
  `holder_name` CHAR(20) NOT NULL,
  `card_type` VARCHAR(20) NOT NULL,
  `CVV` CHAR(3) NOT NULL,
  `expiry` DATE NOT NULL,
  `Customer_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`card_no`, `card_type`, `Customer_email`),
  INDEX `fk_CardInfo_Customer1_idx` (`Customer_email` ASC),
  CONSTRAINT `fk_CardInfo_Customer1`
    FOREIGN KEY (`Customer_email`)
    REFERENCES `myapp`.`Customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Admin` (
  `staff_email` VARCHAR(20) NOT NULL,
  `name` CHAR(60) NOT NULL,
  `department` CHAR(20) NOT NULL,
  `access_rights` CHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`staff_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Update`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Update` (
  `staff_id` VARCHAR(20) NOT NULL,
  `ISBN13` CHAR(14) NOT NULL,
  `last_update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`last_update`, `staff_id`, `ISBN13`),
  INDEX `fk_Update_Product1_idx` (`ISBN13` ASC),
  CONSTRAINT `fk_Update_Admin1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `myapp`.`Admin` (`staff_email`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Update_Product1`
    FOREIGN KEY (`ISBN13`)
    REFERENCES `myapp`.`Product` (`ISBN13`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
